language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t minhcuongphan/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true minhcuongphan/react-test npm test
after_success:
  - docker build -t minhcuongphan/multi-client ./client
  - docker build -t minhcuongphan/multi-nginx ./nginx
  - docker build -t minhcuongphan/multi-server ./server
  - docker build -t minhcuongphan/multi-worker ./worker
  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to the docker hub
  - docker push minhcuongphan/multi-client
  - docker push minhcuongphan/multi-nginx
  - docker push minhcuongphan/multi-server
  - docker push minhcuongphan/multi-worker 
